worker_num: 1
metric: COCO
num_classes: 3

EvalDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/train.json
    dataset_dir: ../dataset/xd
    data_fields: ['image', 'gt_bbox', 'gt_class']

EvalReader:
  sample_transforms:
  - Decode: {}
    # generate multiple samples from Sliding Window
  - SlidingWindow: {input_size: [1280,768], stride: [40, 40], window: [500, 400]}
  - Resize: {target_size: [1152, 3333], keep_ratio: True, interp: 2}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32, pad_gt: false}
  batch_size: 1
  shuffle: false
  drop_last: false
  drop_empty: false
